### :red_circle: Big data error :red_circle:
I tested the completeness of the data and found a few gaps there.
Is this bug or not?

For chceck data I write skript:
> python3 done_check_data.py --action show --file file_new.csv --interval 1m

Script check data for gaps every minute.
A very bad result is the missing data:
```
>>> 1581213540000
>>> 1581217200000
>>> 2020-02-09 01:59:00
>>> 2020-02-09 03:00:00
>>> 3660000
>>> Time delta (1m) 61

>>> 1582112100000
>>> 1582133400000
>>> 2020-02-19 11:35:00
>>> 2020-02-19 17:30:00
>>> 21300000
>>> Time delta (1m) 355

>>> 1583313660000
>>> 1583321400000
>>> 2020-03-04 09:21:00
>>> 2020-03-04 11:30:00
>>> 7740000
>>> Time delta (1m) 129

>>> 1587779940000
>>> 1587789000000
>>> 2020-04-25 01:59:00
>>> 2020-04-25 04:30:00
>>> 9060000
>>> Time delta (1m) 151

>>> 1593309540000
>>> 1593322200000
>>> 2020-06-28 01:59:00
>>> 2020-06-28 05:30:00
>>> 12660000
>>> Time delta (1m) 211

>>> 1606715940000
>>> 1606719600000
>>> 2020-11-30 05:59:00
>>> 2020-11-30 07:00:00
>>> 3660000
>>> Time delta (1m) 61

>>> 1608559680000
>>> 1608573600000
>>> 2020-12-21 14:08:00
>>> 2020-12-21 18:00:00
>>> 13920000
>>> Time delta (1m) 232

>>> 1608861540000
>>> 1608865200000
>>> 2020-12-25 01:59:00
>>> 2020-12-25 03:00:00
>>> 3660000
>>> Time delta (1m) 61
```
